### ISSUE TITLE
Work plan and enhancement / 工作计划和用户诉求

### ISSUE THREAD

**Issue by zRzRzRzRzRzRzR** [THUDM/CogVideo#194]
Tasks that have been identified and scheduled:

+ Fine-tuning support for Diffusers version models 
+ Adaptation for CPU / NPU inference frameworks (e.g., Huawei, Intel devices) 
+ ComfyUI adaptation work and plugin support

已经明确并排期的任务：

+ CogVideoX1.5 Diffusers版本适配
+ CogVideoX-Factory等生态工具的更新

如果你有更多诉求，欢迎在这里提出

**Comment by zRzRzRzRzRzRzR** [comment]
#182 #191 #47 #84 have similar content, all looking forward to the open-source CogVideoX I2V model. We are conducting research and evaluation.

**Comment by rookiemann** [comment]
5b image to video please! I2V would be lovely!

**Comment by PR-Ryan** [comment]
The 3D VAE model consumes significantly more memory during inference compared to diffusion models, which is severely limiting the batch size for fine-tuning. Any suggestions or optimizations to reduce memory usage would be greatly appreciated.

**Comment by zRzRzRzRzRzRzR** [comment]
> The 3D VAE model consumes significantly more memory compared to diffusion models, which is severely limiting the batch size for fine-tuning. Any suggestions or optimizations to reduce memory usage would be greatly appreciated.

You make a very good point. We will work together with the Diffusers team to modify the fake quantization (fakecp) process in the VAE section to optimize it for lower memory usage. Please give us some time, as we will collaborate with the Diffusers team to develop a version of the model that is fine-tuned specifically for Diffusers, which is expected to save a significant amount of memory.

**Comment by zRzRzRzRzRzRzR** [comment]
We are currently completing several tasks
1. Adaptation work for the I2V model, expected to be open-sourced in September
Detailed tutorial on model fine-tuning, expected to be completed in September

Work that has been completed

1. The model fine-tuned with SAT can be converted to a diffusers model and mounted directly. For specific usage, see [here](https://github.com/THUDM/CogVideo/tree/main/sat#using-the-fine-tuned-model)
2. The new Discord invitation link will be merged into the main branch today

**Comment by sincerity711** [comment]
When will vertical video generation be supported?

**Comment by zRzRzRzRzRzRzR** [comment]
> When will vertical video generation be supported?

The current model cannot generate vertical videos, such as 480x720 resolution. We are working on fine-tuning to reach this capability, but it’s still in progress. Once we have any updates, we will share them as soon as possible.

**Comment by zRzRzRzRzRzRzR** [comment]
Two related issues working now:
1.	Diffusers supports CogVideoX-I2V. This [PR](https://github.com/huggingface/diffusers/pull/9418) has been merged, but the patch has not yet been released.

2.	Fine-tuning the Diffusers version of CogVideoX-2B T2V without using the SAT model, running directly under the Diffusers framework. It can run on a single A100 GPU.
This [PR](https://github.com/huggingface/diffusers/pull/9302) is still under debugging. I am working with members of the Diffusers team to attempt fine-tuning the CogVideoX-5B and I2V models. We will provide a small dataset (a few dozen samples) for this PR, which is sufficient for LoRA fine-tuning CogVideoX.

Many thanks to @a-r-r-o-w for the help with these two tasks!

**Comment by JH-Xie** [comment]
when will  CogVideoX-2B-I2V be released?



<br class="Apple-interchange-newline">

**Comment by SanGilbert** [comment]
1. Various resolution support. Maybe RoPE + resize data to random resolution will achieve this?
2. Control ability of model, more than just text prompt.

**Comment by Florenyci** [comment]
@zRzRzRzRzRzRzR Many thanks to you and the team! I know fine-tuning vae is not very useful, but I'm curious is there any way I can just fine-tuning decoder part?

**Comment by zRzRzRzRzRzRzR** [comment]
Our publicly available fine-tuning code is for the fine-tuning of the transformers part, not for vae. We indeed have not updated the training and fine-tuning parts of vae (because I have not received the corresponding permissions either).
Additionally, fine-tuning vae alone seems to have little significance for the overall model effect. If you want to try fine-tuning the diffusers model, all fine-tuning of the transformers module is already in dev, currently it is lora, and it is expected to implement SFT by early October.

**Comment by Florenyci** [comment]
> Our publicly available fine-tuning code is for the fine-tuning of the transformers part, not for vae. We indeed have not updated the training and fine-tuning parts of vae (because I have not received the corresponding permissions either). Additionally, fine-tuning vae alone seems to have little significance for the overall model effect. If you want to try fine-tuning the diffusers model, all fine-tuning of the transformers module is already in dev, currently it is lora, and it is expected to implement SFT by early October.

@zRzRzRzRzRzRzR thank you but actually I'm asking how to fine-tuning VAE decoder, any advice?

**Comment by chenshuo20** [comment]
Hi @zRzRzRzRzRzRzR, what's your plan about diffuser I2V lora fine-tune code? Thanks!

**Comment by alfredplpl** [comment]
Thank you for your great works!

I would like to a full-finetuned model weight in sat into a model weight in diffusers.
My full-finetuned model weight in sat is approx. 22GB.
This model weight may includes transformer and optimizer weight and so on.
Therefore, I tried to extract transformer from the model weight only.
However, something went on.

How can I do it?

**Comment by alfredplpl** [comment]
I could convert the full-finetuned weight into the diffusers weight.
We need extract limited keys by the script:
```python
import torch

# ファイルAとファイルBのパス
file_a_path = 'file_a.pt'
file_b_path = 'file_b.pt'
file_c_path = 'file_c.pt'

# ファイルAをロードしてキーを取得
file_a = torch.load(file_a_path)

# ファイルBをロード
file_b = torch.load(file_b_path)

# 新しいファイルCに入れるデータを保存する辞書
file_c_data = {}

# 再帰的に辞書のキーに基づいて値を取り出す関数
def extract_values_from_b(a_dict, b_dict):
    result = {}
    for key, value in a_dict.items():
        if isinstance(value, dict):  # 値がさらに辞書の場合は再帰処理
            if key in b_dict and isinstance(b_dict[key], dict):
                result[key] = extract_values_from_b(value, b_dict[key])
            else:
                print(f"Key '{key}' not found or not a dict in file B")
        else:
            if key in b_dict:
                result[key] = b_dict[key]
            else:
                print(f"Key '{key}' not found in file B")
    return result

# ファイルAの構造に基づいてファイルBから値を取得
file_c_data = extract_values_from_b(file_a, file_b)

# 新しいファイルCに保存
torch.save(file_c_data, file_c_path)

print(f"New .pt file saved at: {file_c_path}")
```

Please feel free to ask me for further detail.

**Comment by dushwe** [comment]
video outpainting fintune scripts

**Comment by jumbo-q** [comment]
![image](https://github.com/user-attachments/assets/bd226f67-f9a6-4bb5-8431-4193b7d00c8f)


I want to enable multiple gpus, but it go wrong

    # 3. Enable CPU offload for the model.
    # turn off if you have multiple GPUs or enough GPU memory(such as H100) and it will cost less time in inference
    # and enable to("cuda")

    pipe.to("cuda")

    # pipe.enable_sequential_cpu_offload()

    pipe.vae.enable_slicing()
    pipe.vae.enable_tiling()




$ python cli_demo.py --prompt "A girl riding a bike." --model_path THUDM/CogVideoX-5b --generate_type "t2v"
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.13s/it]
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████| 5/5 [00:06<00:00,  1.37s/it]
Traceback (most recent call last):
  File "/home/ubuntu/gamehub/CogVideo/inference/cli_demo.py", line 177, in <module>
    generate_video(
  File "/home/ubuntu/gamehub/CogVideo/inference/cli_demo.py", line 99, in generate_video
    pipe.to("cuda")
  File "/opt/conda/envs/cogvideo/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 396, in to
    raise ValueError(
ValueError: It seems like you have activated sequential model offloading by calling `enable_sequential_cpu_offload`, but are now attempting to move the pipeline to GPU. This is not compatible with offloading. Please, move your pipeline `.to('cpu')` or consider removing the move altogether if you use sequential offloading.

**Comment by zRzRzRzRzRzRzR** [comment]
我们正在适配CogVideoX的diffusers版本代码，预计在11月17日左右完成开源工作，届时，显存消耗会大量降低。敬请期待

**Comment by nitinmukesh** [comment]
The code and all weights works fine on 8Gb VRAM. The 1.5 is slow but it's understood as the resolution is high.

Please consider releasing 480x720 resolution models for vertical videos, if possible.

**Comment by nitinmukesh** [comment]
Requesting to have 2 cli.py for v1 and v1.5 models. I think It's getting confusing regarding resolution, etc. Having different inference file will help.
cli_demo_v1.py
cli_demo_v1.5.py

reference issue: https://github.com/THUDM/CogVideo/issues/517

**Comment by zRzRzRzRzRzRzR** [comment]
The brand new fine-tuning work for the models of the diffusers version will be completed in these two PRs
https://github.com/THUDM/CogVideo/pull/654
2. https://github.com/THUDM/CogVideo/pull/642
At that time, the diffusers version of the CogVideoX 1.0 and 1.5 models will have a more user-friendly and lower-cost Lora and SFT fine-tuning solution compared to before.

**Comment by nini0919** [comment]
> The inversion function is important for some editing tasks. Will the cogvideoX implement related interfaces?

Same question!

**Comment by Griphen116** [comment]
@zRzRzRzRzRzRzR still have any plans/work done for a native ComfyUI node support?
Would greatly appreciate it for the hobbyist space. 🙏

**Comment by zRzRzRzRzRzRzR** [comment]
> The inversion function is important for some editing tasks. Will the cogvideoX implement related interfaces?

This [PR](https://github.com/THUDM/CogVideo/pull/709) may mention your concerns, but it currently does not support CogVideoX-2B; for the 5B model, it can work normally.

**Comment by zRzRzRzRzRzRzR** [comment]
Does the user [@zRzRzRzRzRzRzR](https://github.com/zRzRzRzRzRzRzR) still have any plans/work done for native ComfyUI node support?
We currently do not have enough manpower to support the full development of ComfyUI, but I have noticed that there is similar work in the community that can support it.

**Comment by zRzRzRzRzRzRzR** [comment]
> [@zRzRzRzRzRzRzR](https://github.com/zRzRzRzRzRzRzR) still have any plans/work done for a native ComfyUI node support? Would greatly appreciate it for the hobbyist space. 🙏


We currently do not have enough manpower to support the full development of ComfyUI, but I have noticed that there is similar work in the community that can support it.

**Comment by Haodong-Lei-Ray** [comment]
飞书的计划怎么没有了

**Comment by Haodong-Lei-Ray** [comment]
飞书的技术文档怎么没有了

**Comment by zRzRzRzRzRzRzR** [comment]
> 飞书的技术文档怎么没有了
> 
> ![Image](https://github.com/user-attachments/assets/82442229-15db-439e-bd7f-c2c245e66dd5)

https://zhipu-ai.feishu.cn/wiki/DHCjw1TrJiTyeukfc9RceoSRnCh

**Comment by apihmnizann** [comment]
https://github.com/THUDM/CogVideo/issues/194
