### ISSUE TITLE
RuntimeError: The size of tensor a (33) must match the size of tensor b (16) at non-singleton dimension 2

### ISSUE THREAD

**Issue by panpan0000** [THUDM/CogVideo#351]
### System Info / 系統信息

Aliyun DSW - T4 GPU

CUDA/Driver version:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 12.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10          On   | 00000000:00:07.0 Off |                    0 |
|  0%   33C    P0    55W / 150W |   1604MiB / 22731MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
```

code head : 8da370c2cef49afdaff6fe5321a83947924c2528

```
pip freeze 
transformers @ git+https://github.com/huggingface/transformers.git@409fcfdfccde77a14b7cc36972b774cabc371ae1
xformers==0.0.28.post1
```

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

```
python cli_demo.py  --model_path /mnt/workspace/model/CogVideoX-Fun-5b-InP --prompt "A girl riding a bike" --generate_type "t2v" --dtype fp8 
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  7.03it/s]
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  5.83it/s]
/usr/local/lib/python3.10/site-packages/apex/normalization/fused_layer_norm.py:214: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=False):




  0%|                                                                                                                                                                           | 0/50 [00:38<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/workspace/CogVideo/inference/cli_demo.py", line 177, in <module>
    generate_video(
  File "/mnt/workspace/CogVideo/inference/cli_demo.py", line 121, in generate_video
    video_generate = pipe(
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/pipelines/cogvideo/pipeline_cogvideox.py", line 694, in __call__
    latents, old_pred_original_sample = self.scheduler.step(
  File "/usr/local/lib/python3.10/site-packages/diffusers/schedulers/scheduling_dpm_cogvideox.py", line 411, in step
    pred_original_sample = (alpha_prod_t**0.5) * sample - (beta_prod_t**0.5) * model_output
RuntimeError: The size of tensor a (33) must match the size of tensor b (16) at non-singleton dimension 2
```

### Expected behavior / 期待表现

no error

**Comment by zRzRzRzRzRzRzR** [comment]
额，这个GPU不支持FP8吧 你先用cli_demo试试
