### ISSUE TITLE
Text to video and video to video doesn't work  

### ISSUE THREAD

**Issue by FurkanGozukara** [THUDM/CogVideo#368]
when no cpu offloading is used, text to video loads 20.4 GB and just waits

when cpu offloading used, text to video gives below error

video to video gives below error at all cases whether cpu offloading or not

I am using the app shared here on ubuntu on L40S and on my pc : https://huggingface.co/spaces/THUDM/CogVideoX-5B-Space

image to video works perfect though no issues in both ways

```
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "R:\CogVideoX_v1\CogVideoX_SECourses\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "R:\CogVideoX_v1\CogVideoX_SECourses\venv\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "R:\CogVideoX_v1\CogVideoX_SECourses\venv\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "R:\CogVideoX_v1\CogVideoX_SECourses\venv\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "R:\CogVideoX_v1\CogVideoX_SECourses\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "R:\CogVideoX_v1\CogVideoX_SECourses\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "R:\CogVideoX_v1\CogVideoX_SECourses\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "R:\CogVideoX_v1\CogVideoX_SECourses\venv\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "R:\CogVideoX_v1\CogVideoX_SECourses\venv\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "R:\CogVideoX_v1\CogVideoX_SECourses\app.py", line 340, in generate
    latents, seed = infer(
  File "R:\CogVideoX_v1\CogVideoX_SECourses\app.py", line 206, in infer
    video_pt = pipe_video(
  File "R:\CogVideoX_v1\CogVideoX_SECourses\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "R:\CogVideoX_v1\CogVideoX_SECourses\venv\lib\site-packages\diffusers\pipelines\cogvideo\pipeline_cogvideox_video2video.py", line 725, in __call__
    latents = self.prepare_latents(
  File "R:\CogVideoX_v1\CogVideoX_SECourses\venv\lib\site-packages\diffusers\pipelines\cogvideo\pipeline_cogvideox_video2video.py", line 392, in prepare_latents
    latents = self.scheduler.add_noise(init_latents, noise, timestep)
  File "R:\CogVideoX_v1\CogVideoX_SECourses\venv\lib\site-packages\diffusers\schedulers\scheduling_dpm_cogvideox.py", line 465, in add_noise
    noisy_samples = sqrt_alpha_prod * original_samples + sqrt_one_minus_alpha_prod * noise
RuntimeError: The size of tensor a (16) must match the size of tensor b (32) at non-singleton dimension 2



```

```
Traceback (most recent call last):
  File "/workspace/ImageToVideoAI/venv/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/workspace/ImageToVideoAI/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/workspace/ImageToVideoAI/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/workspace/ImageToVideoAI/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/workspace/ImageToVideoAI/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/workspace/ImageToVideoAI/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "/workspace/ImageToVideoAI/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "/workspace/ImageToVideoAI/venv/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/workspace/ImageToVideoAI/venv/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/workspace/ImageToVideoAI/app.py", line 340, in generate
    latents, seed = infer(
  File "/workspace/ImageToVideoAI/app.py", line 206, in infer
    video_pt = pipe_video(
  File "/workspace/ImageToVideoAI/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/ImageToVideoAI/venv/lib/python3.10/site-packages/diffusers/pipelines/cogvideo/pipeline_cogvideox_video2video.py", line 725, in __call__
    latents = self.prepare_latents(
  File "/workspace/ImageToVideoAI/venv/lib/python3.10/site-packages/diffusers/pipelines/cogvideo/pipeline_cogvideox_video2video.py", line 392, in prepare_latents
    latents = self.scheduler.add_noise(init_latents, noise, timestep)
  File "/workspace/ImageToVideoAI/venv/lib/python3.10/site-packages/diffusers/schedulers/scheduling_dpm_cogvideox.py", line 465, in add_noise
    noisy_samples = sqrt_alpha_prod * original_samples + sqrt_one_minus_alpha_prod * noise
RuntimeError: The size of tensor a (16) must match the size of tensor b (32) at non-singleton dimension 2
```

pip freeze

```


(venv) R:\CogVideoX_v1\CogVideoX_SECourses>pip freeze
accelerate==0.34.2
aiofiles==23.2.1
annotated-types==0.7.0
anyio==4.6.0
certifi==2024.8.30
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
contourpy==1.3.0
cycler==0.12.1
decorator==4.4.2
diffusers @ git+https://github.com/huggingface/diffusers.git@665c6b47a23bc841ad1440c4fe9cbb1782258656
distro==1.9.0
einops==0.8.0
exceptiongroup==1.2.2
fastapi==0.115.0
ffmpy==0.4.0
filelock==3.16.1
fonttools==4.54.1
fsspec==2024.9.0
gradio==4.44.0
gradio_client==1.3.0
h11==0.14.0
httpcore==1.0.5
httpx==0.27.2
huggingface-hub==0.25.1
idna==3.10
imageio==2.35.1
imageio-ffmpeg==0.5.1
importlib_metadata==8.5.0
importlib_resources==6.4.5
Jinja2==3.1.4
jiter==0.5.0
kiwisolver==1.4.7
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.2
mdurl==0.1.2
moviepy==1.0.3
mpmath==1.3.0
networkx==3.3
numpy==1.26.0
openai==1.49.0
opencv-python==4.10.0.84
orjson==3.10.7
packaging==24.1
pandas==2.2.3
Pillow==9.5.0
proglog==0.1.10
psutil==6.0.0
pydantic==2.9.2
pydantic_core==2.23.4
pydub==0.25.1
Pygments==2.18.0
pyparsing==3.1.4
python-dateutil==2.9.0.post0
python-multipart==0.0.10
pytz==2024.2
PyYAML==6.0.2
regex==2024.9.11
requests==2.32.3
rich==13.8.1
ruff==0.6.8
safetensors==0.4.5
scikit-video==1.1.11
scipy==1.14.1
semantic-version==2.10.0
sentencepiece==0.2.0
shellingham==1.5.4
six==1.16.0
sniffio==1.3.1
spandrel==0.4.0
starlette==0.38.6
sympy==1.13.3
tokenizers==0.20.0
tomlkit==0.12.0
torch==2.4.1+cu124
torchvision==0.19.1+cu124
tqdm==4.66.5
transformers==4.45.1
triton @ https://huggingface.co/MonsterMMORPG/SECourses/resolve/main/triton-3.0.0-cp310-cp310-win_amd64.whl
typer==0.12.5
typing_extensions==4.12.2
tzdata==2024.2
urllib3==2.2.3
uvicorn==0.30.6
websockets==12.0
xformers==0.0.28.post1
zipp==3.20.2

(venv) R:\CogVideoX_v1\CogVideoX_SECourses>
```

**Comment by panpan0000** [comment]
t2v & v2v use model CogVideoX-5B
and i2v uses model CogVideoX-5B-i2v

wrong model will trigger this kind of error

**Comment by FurkanGozukara** [comment]
thank you for answers @zRzRzRzRzRzRzR @panpan0000 

already using accurate pipes - taken code from your demo page

`pipe = CogVideoXPipeline.from_pretrained("THUDM/CogVideoX-5b", torch_dtype=default_dtype).to("cpu")`


![image](https://github.com/user-attachments/assets/c971f375-07b7-4eba-b73f-e29ec2e4d2f3)

![image](https://github.com/user-attachments/assets/78f9bbf0-0800-4e3d-a559-189e831a3d30)

![image](https://github.com/user-attachments/assets/22283419-d00f-40d7-85f1-42ed9cedcdd5)

**Comment by FurkanGozukara** [comment]
here my entire app py you can see i am using the demo you shared

[app.txt](https://github.com/user-attachments/files/17161645/app.txt)
