### ISSUE TITLE
cogVideoX1.5-5B pipeline is very slow

### ISSUE THREAD

**Issue by zqhi71** [THUDM/CogVideo#545]
### System Info / 系統信息

ubuntu:20.04
cuda: 12.4
pytorch: 2.5.1
torchao: 0.6.1
diffusers: main branch (last commit: b5fd6f13f5434d69d919cc8cedf0b11db664cf06)
python: 3.10

GPU: NVIDIA RTX 4090

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

download model into '/root/models/CogVideoX1.5-5B'

run huggingface model page quick start example (standard or quantized) only change the model path to local file.

GPU usage has reached 100% (but only 110w, fig1), and after waiting for a long time（at least an hour）, it's still at 0/50. When I cancel by ctrl+c, the traceback shows in fig2. If I comment out pipe.enable_sequential_cpu_offload, the model cannot be loaded into the GPU (even using pipe.to('cuda:0') does not work).  Is this normal? (CogVideoX-5B works fine in same environment.)

![fig1](https://github.com/user-attachments/assets/18a41aae-3ff2-4016-8478-b303dd31a097)

![fig2](https://github.com/user-attachments/assets/b91fca42-1ece-4372-b002-92a0eda86c5c)

### Expected behavior / 期待表现

achieving normal efficiency on the GPU

**Comment by AvisP** [comment]
I have the same issue as well, I ran the code provided in the previous post on A100-80GB and CogVideoX1.5-5B text to video takes 30 mins to generate a video with `num_inference_step` set to 10 only. While with CogVideoX-5b it takes less than a minute. Please fix the pipeline,

**Comment by zRzRzRzRzRzRzR** [comment]
The computational load of CogVideoX-5B is about one-fourth of CogVideoX1.5-5B. Therefore, you should multiply the time of CogVideoX-5B by 4. If your generation time is 10 seconds, then you also need to generate 5 seconds of time * 4 times in CogVideoX1.5-5B. If you are using A100, I suggest you turn off cpu_offload and turn on pipe.to("cuda"). 1000 seconds can generate a 5-second video.

**Comment by AvisP** [comment]
Thanks for your comment. I double checked if the optimizations are turned off and reran as you suggested but it still takes a huge amount of time to execute. Following is the code that I am using

```
import torch
from diffusers import CogVideoXPipeline, CogVideoXDPMScheduler
from diffusers.utils import export_to_video
import time
        
subprocess.run(["nvidia-smi"])
torch.cuda.empty_cache()
print(torch.cuda.memory_allocated()/1024**2)
print(torch.cuda.memory_reserved()/1024**2)

pipe = CogVideoXPipeline.from_pretrained(MODEL_PATH, torch_dtype=torch.bfloat16)
pipe.scheduler = CogVideoXDPMScheduler.from_config(pipe.scheduler.config, timestep_spacing="trailing")
pipe.to("cuda")       

#prompt = "A cat holding a sign that says hello world"

prompt: str = (
        "A garden comes to life as a kaleidoscope of butterflies flutters amidst the blossoms, "
        "their delicate wings casting shadows on the petals below. In the background, a grand fountain "
        "cascades water with a gentle splendor, its rhythmic sound providing a soothing backdrop. Beneath "
        "the cool shade of a mature tree, a solitary wooden chair invites solitude and reflection, its smooth "
        "surface worn by the touch of countless visitors seeking a moment of tranquility in nature's embrace."
    )
    
num_videos_per_prompt = 1
use_dynamic_cfg_flag = True
guidance_scale = 6.0
manual_seed = 4567

start = time.time()

video = self.pipe(
    prompt=prompt,
    num_videos_per_prompt=num_videos_per_prompt,  # Number of videos to generate per prompt
    num_inference_steps=num_inference_steps,  # Number of inference steps
    num_frames=81,  # Number of frames to generate，changed to 49 for diffusers version `0.31.0` and after.
    use_dynamic_cfg=use_dynamic_cfg_flag,  ## This id used for DPM Sechduler, for DDIM scheduler, it should be False
    guidance_scale=guidance_scale,  # Guidance scale for classifier-free guidance, can set to 7 for DPM scheduler
    generator=torch.Generator(device="cuda").manual_seed(manual_seed),  # Set the seed for reproducibility
).frames[0]

print("Time taken ", time.time()-start)

output_path = volume_path / "runs"
output_path.mkdir(parents=True, exist_ok=True)
output_file_path =  Path.joinpath(output_path, 'output.mp4')
```

This code has already been running for close to 30 mins and is not even at inference step 4. Based on the values you provided it should have finished in less than 1000 secs or about 17 mins but that doesn't seem to be the case. Is there any issue with the code segment and if not is it possible to check somehow on your end?

![image](https://github.com/user-attachments/assets/2c2b5736-e8ec-4b54-8809-7dc0971e2660)

Hardware and Cuda info
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          On  |   00000000:80:03.0 Off |                    0 |
| N/A   43C    P0             68W /  400W |       1MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

**Comment by zRzRzRzRzRzRzR** [comment]
Please set the default height and width, otherwise it will be 2400 * 2400 (in order to achieve different I2V, for normal operation, if you are t2v, please set weight = 1360, height = 768 to work properly, just like our cli demo).
In addition, what does self mean?
```
video = self.pipe(
```
Why not use pipe(.) directly?

**Comment by AvisP** [comment]
Thank you for your prompt response. I added the weight and height and the inference time has come down to about 3 mins! I was following the huggingface [example](https://huggingface.co/THUDM/CogVideoX1.5-5B) which doesn't specify these two parameters needs to be set. You may want to consider modifying it there else others may report issues. 

Please ignore the `self.pipe` I was using a python class and it got copied over from there. 

However there is still a small issue, looks like without the optimization it runs out of the 80 GB gpu memory as I am getting the following error. I tried to get the latest version of docker issued by nvidia (nvidia/cuda:12.6.2-cudnn-devel-ubuntu22.04) but looks like that also don't have the version 9.5.1 of cudnn. If you have any suggestions how to got about this or enable the `v8 API` let me know. Thanks again!

```
Loading checkpoint shards: 100%|██████████| 4/4 [00:11<00:00,  2.91s/it]it/s]
Loading pipeline components...: 100%|██████████| 5/5 [00:18<00:00,  3.62s/it]
100%|██████████| 10/10 [02:58<00:00, 17.80s/it]
/usr/local/lib/python3.11/site-packages/torch/nn/modules/conv.py:720: UserWarning: cuDNN cannot be used for large non-batch-splittable convolutions if the V8 API is not enabled or before cuDNN version 9.3+. Consider upgrading cuDNN and/or enabling the V8 API for better efficiency. (Triggered internally at ../aten/src/ATen/native/Convolution.cpp:430.)
  return F.conv3d(
Traceback (most recent call last):
Stopping app - uncaught exception raised locally: OutOfMemoryError('CUDA out of memory. Tried to allocate 3.98 GiB. GPU 0 has a total capacity of 79.14 GiB of which 1.52 GiB is free. Process 3386712 has 77.61 GiB memory in use. Of the allocated memory 54.21 GiB is allocated by PyTorch, and 22.89 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)').
  File "/pkg/modal/_container_io_manager.py", line 508, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 383, in run_input_sync
    res = finalized_function.callable(*local_input.args, **local_input.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/CogVideo_1_5B_test.py", line 174, in inference
    return self._inference(
           ^^^^^^^^^^^^^^^^
  File "/root/CogVideo_1_5B_test.py", line 146, in _inference
    video = self.pipe(
            ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diffusers/pipelines/cogvideo/pipeline_cogvideox.py", line 761, in __call__
    video = self.decode_latents(latents)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diffusers/pipelines/cogvideo/pipeline_cogvideox.py", line 350, in decode_latents
    frames = self.vae.decode(latents).sample
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py", line 1287, in decode
    decoded = self._decode(z).sample
              ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py", line 1258, in _decode
    z_intermediate, conv_cache = self.decoder(z_intermediate, conv_cache=conv_cache)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py", line 978, in forward
    hidden_states, new_conv_cache[conv_cache_key] = up_block(
                                                    ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py", line 655, in forward
    hidden_states, new_conv_cache[conv_cache_key] = resnet(
                                                    ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py", line 299, in forward
    hidden_states, new_conv_cache["norm1"] = self.norm1(hidden_states, zq, conv_cache=conv_cache.get("norm1"))
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py", line 194, in forward
    norm_f = self.norm_layer(f)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/normalization.py", line 313, in forward
    return F.group_norm(input, self.num_groups, self.weight, self.bias, self.eps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/functional.py", line 2955, in group_norm
    return torch.group_norm(
           ^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.98 GiB. GPU 0 has a total capacity of 79.14 GiB of which 1.52 GiB is free. Process 3386712 has 77.61 GiB memory in use. Of the allocated memory 54.21 GiB is allocated by PyTorch, and 22.89 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

**Comment by AvisP** [comment]
Update : I managed to do the inference with the optimizations on a A100-80GB. I upgraded the cudnn to 9.5.1 but the error as mentioned earlier didn't go away. With the following optimizations enables it takes about a minute longer to complete.

```
pipe.enable_sequential_cpu_offload()
pipe.vae.enable_slicing()
pipe.vae.enable_tiling()   
```
Is it possible to verify if the model runs without needing optimization on A100 80GB? Thanks!

**Comment by townwish4git** [comment]
Exactly the same as the problem I encountered. I agree that the use cases on the huggingface model homepage should emphasize the settings of these two parameters

**Comment by zRzRzRzRzRzRzR** [comment]
After adding pipe.enable_sequential_cpu_offload(), the speed is significantly slower, which is normal, but I don't understand why removing it causes your A100 to run out of memory, with the normal usage being around 40G.

**Comment by townwish4git** [comment]
> After adding pipe.enable_sequential_cpu_offload(), the speed is significantly slower, which is normal, but I don't understand why removing it causes your A100 to run out of memory, with the normal usage being around 40G.

I met the same memory issue, without `enable_sequential_cpu_offload` A100 80G is running out of memory:
- torch2.5.1+cu121
- diffusers master(The most recent version from the past 1 or 2days)
- CogVideo1.5 T2I with argument `(num_frames, width, height) = (81, 1360, 768)`

it cost 30-40GB at most when DiT running, when VAE decoding it raised error about OOM

**Comment by townwish4git** [comment]
maybe we could ask some huggingface friends for help, @a-r-r-o-w

**Comment by a-r-r-o-w** [comment]
Hi, thanks for the ping about this issue.

`enable_sequential_cpu_offload` is indeed a very slow optimization for memory. This is because it only loads one underlying `nn.Module` at a time on the GPU, performs computation, and moves the module back to the CPU. This introduces a lot of cuda stream synchronizations and additional wait times where no computation happens. There is an internal discussion going on about how we could optimize this a bit using async stream transfer for modules and prefetching the next required layer - but this will take a long time to get integrated. The idea is well tested and inspired from this post: https://x.com/gaunernst/status/1859192060966011032 if you would like to give it a try.

Also, maybe you could try `enable_model_cpu_offload` instead and see if that meets the requirements of being fast without using too much memory? Also, slicing is useful only when you have a batch_size > 1. Tiling is done in small 240x360 spatial tiles at the moment, but you could try reducing it by referring to internal implementation details ([here](https://github.com/huggingface/diffusers/blob/cfdeebd4a8f0decc3d0e1f0f05a7112ddd1e0a29/src/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py#L1112)) to see see if it helps.

**Comment by townwish4git** [comment]
Ohhh, maybe AvisP and me ran out of memory but ZR said 'but I don't understand why removing it causes your A100 to run out of memory, with the normal usage being around 40G.' is because: 

ZR tests with vae_slicing & vae_tiling is ON and AvisP and me turn them off. 

Is that right brothers? @AvisP @zRzRzRzRzRzRzR

**Comment by MyCroniesSoft** [comment]
Using sora made my eye balls drop, 20 second video at 1080p extended mode, made my eyes think, but for 200 a month i can see saturation in the first month of december and january.

Renting a gpu for trainning and not having access to a h200 and the frustration.

The only thing i see is tencents version to the opensource version really cutting into sora, but hardly anymodel can run it effectly, cogx5 is impressive, but not there, impressive because you can access it via api calls in command line, when that happens for sora or tencent you can make api calls then omg will automation be crazy.

**Comment by AvisP** [comment]
@townwish4git Apologies for the delayed response but I carried out some tests with turning things on and off and here is what I observed. I tried to generate a video with image of height 1360 and width 768 with 20 inference step with some prompt

With the following turned on, time taken 7:49 
```
pipe.enable_sequential_cpu_offload()
pipe.vae.enable_slicing()
pipe.vae.enable_tiling()
```

With only `pipe.enable_sequential_cpu_offload()` it took about 7:47

With `pipe.enable_model_cpu_offload()` as mentioned by a-r-r-o-w it was indeed bit faster taking about `6:03`

And with none of them applied and with `pipe.to('cuda')` I am still getting out of CUDA memory.

**Comment by zRzRzRzRzRzRzR** [comment]
This is normal, 1.5 generates a video in about 900 seconds, which is roughly 15 minutes.
