### ISSUE TITLE
CogVideoX1.5-5B-I2V  run failed. assert len(timesteps.shape) == 1, "Timesteps should be a 1d-array"

### ISSUE THREAD

**Issue by chenpinganan** [THUDM/CogVideo#574]
### System Info / 系統信息

Package                  Version     Editable project location
------------------------ ----------- -------------------------
accelerate               1.1.1
aiofiles                 23.2.1
aiohappyeyeballs         2.4.4
aiohttp                  3.11.9
aiosignal                1.3.1
annotated-types          0.7.0
anyio                    4.6.2.post1
attrs                    24.2.0
boto3                    1.35.72
botocore                 1.35.72
braceexpand              0.1.7
certifi                  2024.8.30
charset-normalizer       3.4.0
click                    8.1.7
cpm-kernels              1.0.11
datasets                 3.1.0
decorator                5.1.1
deepspeed                0.16.0
diffusers                0.32.0.dev0 
dill                     0.3.8
distro                   1.9.0
einops                   0.8.0
fastapi                  0.115.5
ffmpy                    0.4.0
filelock                 3.16.1
frozenlist               1.5.0
fsspec                   2024.9.0
gradio                   5.7.1
gradio_client            1.5.0
h11                      0.14.0
hjson                    3.1.0
httpcore                 1.0.7
httpx                    0.28.0
huggingface-hub          0.26.3
idna                     3.10
imageio                  2.36.1
imageio-ffmpeg           0.5.1
importlib_metadata       8.5.0
Jinja2                   3.1.4
jiter                    0.8.0
jmespath                 1.0.1
markdown-it-py           3.0.0
MarkupSafe               2.1.5
mdurl                    0.1.2
moviepy                  2.1.1
mpmath                   1.3.0
msgpack                  1.1.0
multidict                6.1.0
multiprocess             0.70.16
networkx                 3.4.2
ninja                    1.11.1.2
numpy                    1.26.0
nvidia-cublas-cu12       12.4.5.8
nvidia-cuda-cupti-cu12   12.4.127
nvidia-cuda-nvrtc-cu12   12.4.127
nvidia-cuda-runtime-cu12 12.4.127
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.2.1.3
nvidia-curand-cu12       10.3.5.147
nvidia-cusolver-cu12     11.6.1.9
nvidia-cusparse-cu12     12.3.1.170
nvidia-nccl-cu12         2.21.5
nvidia-nvjitlink-cu12    12.4.127
nvidia-nvtx-cu12         12.4.127
openai                   1.56.0
orjson                   3.10.12
packaging                24.2
pandas                   2.2.3
pillow                   10.4.0
pip                      24.3.1
proglog                  0.1.10
propcache                0.2.1
protobuf                 5.29.0
psutil                   6.1.0
py-cpuinfo               9.0.0
pyarrow                  18.1.0
pydantic                 2.10.2
pydantic_core            2.27.1
pydub                    0.25.1
Pygments                 2.18.0
python-dateutil          2.9.0.post0
python-dotenv            1.0.1
python-multipart         0.0.12
pytz                     2024.2
PyYAML                   6.0.2
regex                    2024.11.6
requests                 2.32.3
rich                     13.9.4
ruff                     0.8.1
s3transfer               0.10.4
safehttpx                0.1.6
safetensors              0.4.5
scikit-video             1.1.11
scipy                    1.14.1
semantic-version         2.10.0
sentencepiece            0.2.0
setuptools               75.6.0
shellingham              1.5.4
six                      1.16.0
sniffio                  1.3.1
starlette                0.41.3
SwissArmyTransformer     0.4.12
sympy                    1.13.1
tensorboardX             2.6.2.2
tokenizers               0.20.3
tomlkit                  0.12.0
torch                    2.5.1
torchvision              0.20.1
tqdm                     4.67.1
transformers             4.46.3
triton                   3.1.0
typer                    0.14.0
typing_extensions        4.12.2
tzdata                   2024.2
urllib3                  2.2.3
uvicorn                  0.32.1
webdataset               0.2.100
websockets               12.0
wheel                    0.45.1
xxhash                   3.5.0
yarl                     1.18.3
zipp                     3.21.0

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. install diffusers  by source
2. test-code copy from https://modelscope.cn/models/ZhipuAI/CogVideoX1.5-5B

‘’’
import torch
from diffusers import CogVideoXPipeline
from diffusers.utils import export_to_video

prompt = "A panda, dressed in a small, red jacket and a tiny hat, sits on a wooden stool in a serene bamboo forest. The panda's fluffy paws strum a miniature acoustic guitar, producing soft, melodic tunes. Nearby, a few other pandas gather, watching curiously and some clapping in rhythm. Sunlight filters through the tall bamboo, casting a gentle glow on the scene. The panda's face is expressive, showing concentration and joy as it plays. The background includes a small, flowing stream and vibrant green foliage, enhancing the peaceful and magical atmosphere of this unique musical performance."

pipe = CogVideoXPipeline.from_pretrained(
    "CogVideoX1.5-5B-I2V",
    torch_dtype=torch.bfloat16
)

pipe.enable_sequential_cpu_offload()
pipe.vae.enable_tiling()
pipe.vae.enable_slicing()

video = pipe(
    prompt=prompt,
    num_videos_per_prompt=1,
    num_inference_steps=50,
    num_frames=49,
    guidance_scale=6,
    generator=torch.Generator(device="cuda").manual_seed(42),
).frames[0]

export_to_video(video, "output.mp4", fps=8)
‘’’

log is ：
'''
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:04<00:00,  1.04s/it]
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:06<00:00,  1.24s/it]
  0%|                                                                                                                                  | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run_CogVideoX15.py", line 60, in <module>
    video = pipe(
            ^^^^^
  File "lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "diffusers/src/diffusers/pipelines/cogvideo/pipeline_cogvideox.py", line 710, in __call__
    noise_pred = self.transformer(
                 ^^^^^^^^^^^^^^^^^
  File "lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.12/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "diffusers/src/diffusers/models/transformers/cogvideox_transformer_3d.py", line 470, in forward
    ofs_emb = self.ofs_proj(ofs)
              ^^^^^^^^^^^^^^^^^^
  File "lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "diffusers/src/diffusers/models/embeddings.py", line 1028, in forward
    t_emb = get_timestep_embedding(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "diffusers/src/diffusers/models/embeddings.py", line 54, in get_timestep_embedding
    assert len(timesteps.shape) == 1, "Timesteps should be a 1d-array"
               ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'shape'
'''

### Expected behavior / 期待表现

gen video success

**Comment by chenpinganan** [comment]
Should load CogVideoX1.5-5B instead of CogVideoX1.5-5B-I2V
