### ISSUE TITLE
OOM when fine-tune CogVideo5B-Diffusers Model using multi-GPUs

### ISSUE THREAD

**Issue by zyt-yt** [THUDM/CogVideo#575]
### System Info / 系統信息

CUDA Version: 12.2
Python 3.9.20
transformers              4.46.1
accelerate                1.0.1
diffusers                 0.32.0.dev0
Linux

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. create this accelerate_config.yaml file
    ``` 
    compute_environment: LOCAL_MACHINE 
    debug: true
    
    deepspeed_config:
      deepspeed_multinode_launcher: pdsh
      gradient_accumulation_steps: 1
      gradient_clipping: 1.0
      offload_optimizer_device: none
      offload_param_device: none
      zero3_init_flag: true
      zero_stage: 3
    distributed_type: DEEPSPEED
    
    downcast_bf16: 'yes'
    enable_cpu_affinity: true
    main_process_ip: 127.0.0.1
    main_process_port: 12355
    main_training_function: main
    
    mixed_precision: bf16
    num_machines: 1
    num_processes: 3
    gpu_ids: 1,2,3
    rdzv_backend: static
    same_network: true
    
    tpu_env: []
    tpu_use_cluster: false
    tpu_use_sudo: false
    use_cpu: false
    ```
2. run this shell script: bash train.sh
   ```
    #!/bin/bash
    pretrained_model_name_or_path="THUDM/CogVideoX-5b"
    instance_data_root="/data0/xxx/diffusers/datasets2/single_video_openvid"
    output_dir="/data0/xxx/diffusers/datasets2/single_video_openvid/output5b"
    cache_dir="/data0/xxx/diffusers/examples/cogvideo/cache2"
    rank=128
    lora_alpha=128
    mixed_precision="bf16"
    height=512
    width=512
    fps=24
    
    config_file="accelerate_config.yaml"
    
    accelerate launch --config_file $config_file --multi_gpu examples/cogvideo/train_cogvideox_lora.py \
      --pretrained_model_name_or_path $pretrained_model_name_or_path \
      --cache_dir $cache_dir \
      --instance_data_root $instance_data_root \
      --caption_column prompt.txt \
      --video_column videos.txt \
      --id_token 0002 \
      --validation_prompt "<0002> An aerial shot of a small rocky island." \
      --validation_prompt_separator ::: \
      --num_validation_videos 1 \
      --validation_epochs 1 \
      --seed 66 \
      --rank $rank \
      --lora_alpha $lora_alpha \
      --mixed_precision $mixed_precision \
      --output_dir $output_dir \
      --height "$height" --width "$width" --fps "$fps" --max_num_frames 49 --skip_frames_start 0 --skip_frames_end 0 \
      --train_batch_size 1 \
      --num_train_epochs 30 \
      --max_train_steps 1500 \
      --checkpointing_steps 100 \
      --gradient_accumulation_steps 1 \
      --learning_rate 1e-4 \
      --lr_scheduler cosine_with_restarts \
      --lr_warmup_steps 200 \
      --lr_num_cycles 1 \
      --enable_slicing \
      --enable_tiling \
      --optimizer Adam \
      --adam_beta1 0.9 \
      --adam_beta2 0.95 \
      --max_grad_norm 1.0 \
      --report_to wandb
    ```
3. the training will OOM: 
    ```
    [rank2]: Traceback (most recent call last):
    [rank2]:   File "/data0/xxx/diffusers/examples/cogvideo/train_cogvideox_lora.py", line 1634, in <module>
    [rank2]:     main(args)
    [rank2]:   File "/data0/xxx/diffusers/examples/cogvideo/train_cogvideox_lora.py", line 1447, in main
    [rank2]:     model_output = transformer(
    [rank2]:   File "/home/xxx/miniconda3/envs/test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    [rank2]:     return self._call_impl(*args, **kwargs)
    [rank2]:   File "/home/xxx/miniconda3/envs/test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    [rank2]:     return forward_call(*args, **kwargs)
    [rank2]:   File "/home/xxx/miniconda3/envs/test/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1643, in forward
    [rank2]:     else self._run_ddp_forward(*inputs, **kwargs)
    [rank2]:   File "/home/xxx/miniconda3/envs/test/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1459, in _run_ddp_forward
    [rank2]:     return self.module(*inputs, **kwargs)  # type: ignore[index]
    [rank2]:   File "/home/xxx/miniconda3/envs/test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    [rank2]:     return self._call_impl(*args, **kwargs)
    [rank2]:   File "/home/xxx/miniconda3/envs/test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    [rank2]:     return forward_call(*args, **kwargs)
    [rank2]:   File "/home/xxx/miniconda3/envs/test/lib/python3.9/site-packages/accelerate/utils/operations.py", line 820, in forward
    [rank2]:     return model_forward(*args, **kwargs)
    [rank2]:   File "/home/xxx/miniconda3/envs/test/lib/python3.9/site-packages/accelerate/utils/operations.py", line 808, in __call__
    [rank2]:     return convert_to_fp32(self.model_forward(*args, **kwargs))
    [rank2]:   File "/home/xxx/miniconda3/envs/test/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 44, in decorate_autocast
    [rank2]:     return func(*args, **kwargs)
    [rank2]:   File "/data0/xxx/diffusers/src/diffusers/models/transformers/cogvideox_transformer_3d.py", line 473, in forward
    [rank2]:     hidden_states, encoder_hidden_states = block(
    [rank2]:   File "/home/xxx/miniconda3/envs/test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    [rank2]:     return self._call_impl(*args, **kwargs)
    [rank2]:   File "/home/xxx/miniconda3/envs/test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    [rank2]:     return forward_call(*args, **kwargs)
    [rank2]:   File "/data0/xxx/diffusers/src/diffusers/models/transformers/cogvideox_transformer_3d.py", line 132, in forward
    [rank2]:     attn_hidden_states, attn_encoder_hidden_states = self.attn1(
    [rank2]:   File "/home/xxx/miniconda3/envs/test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    [rank2]:     return self._call_impl(*args, **kwargs)
    [rank2]:   File "/home/xxx/miniconda3/envs/test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    [rank2]:     return forward_call(*args, **kwargs)
    [rank2]:   File "/data0/xxx/diffusers/src/diffusers/models/attention_processor.py", line 530, in forward
    [rank2]:     return self.processor(
    [rank2]:   File "/data0/xxx/diffusers/src/diffusers/models/attention_processor.py", line 2285, in __call__
    [rank2]:     query = attn.norm_q(query)
    [rank2]:   File "/home/xxx/miniconda3/envs/test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    [rank2]:     return self._call_impl(*args, **kwargs)
    [rank2]:   File "/home/xxx/miniconda3/envs/test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    [rank2]:     return forward_call(*args, **kwargs)
    [rank2]:   File "/home/xxx/miniconda3/envs/test/lib/python3.9/site-packages/torch/nn/modules/normalization.py", line 217, in forward
    [rank2]:     return F.layer_norm(
    [rank2]:   File "/home/xxx/miniconda3/envs/test/lib/python3.9/site-packages/torch/nn/functional.py", line 2900, in layer_norm
    [rank2]:     return torch.layer_norm(
    [rank2]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 160.00 MiB. GPU 2 has a total capacity of 79.11 GiB of which 160.88 MiB is free. Including non-PyTorch memory, this process has 78.94 GiB memory in use. Of the allocated memory 73.24 GiB is allocated by PyTorch, and 4.78 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
    ...
        raise ChildFailedError(
    torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
    ============================================================
    examples/cogvideo/train_cogvideox_lora.py FAILED
    ------------------------------------------------------------
    Failures:
      <NO_OTHER_FAILURES>
    ------------------------------------------------------------
    Root Cause (first observed failure):
    [0]:
      time      : 2024-12-03_15:24:23
      host      : amax
      rank      : 2 (local_rank: 2)
      exitcode  : 1 (pid: 476877)
      error_file: <N/A>
      traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
    ============================================================
    ```
    
Is anything wrong with my config file or shell cmd?
Thanks!

### Expected behavior / 期待表现

Run well with multiple GPUs when fine-tune CogVideo-5B-diffusers.

**Comment by zyt-yt** [comment]
after I enabled gradient_checkpointing, the fine-tune can run in one GPU.
but I still want to ask:
- Is there any other method
