### ISSUE TITLE
Can the trained LoRA model, CogVideoX-Fun-V1.1-Reward-LoRAs, be used with CogVideoX-5b-I2V?

### ISSUE THREAD

**Issue by mrlihellohorld** [THUDM/CogVideo#591]
### System Info / 系統信息

ubutun

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

            lora_name = 'CogVideoX-Fun-V1.1-5b-InP-HPS2.1.safetensors'
            self.pipe.load_lora_weights(lora_path_root,weight_name=lora_name, adapter_name=adapter_name)
            Use the base model CogVideoX-5b-I2V to load lora:CogVideoX-Fun-V1.1-5b-InP-HPS2.1.safetensors.

### Expected behavior / 期待表现

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/code/ace/CogVideo/smart_g_image_to_video_sobey/app/src/I2VExtensionPackage/diffusers/loaders/lora_pipeline.py", line 2513, in load_lora_weights
    self.load_lora_into_transformer(
  File "/code/ace/CogVideo/smart_g_image_to_video_sobey/app/src/I2VExtensionPackage/diffusers/loaders/lora_pipeline.py", line 2550, in load_lora_into_transformer
    transformer.load_lora_adapter(
  File "/code/ace/CogVideo/smart_g_image_to_video_sobey/app/src/I2VExtensionPackage/diffusers/loaders/peft.py", line 226, in load_lora_adapter
    lora_config_kwargs = get_peft_kwargs(rank, network_alpha_dict=network_alphas, peft_state_dict=state_dict)
  File "/code/ace/CogVideo/smart_g_image_to_video_sobey/app/src/I2VExtensionPackage/diffusers/utils/peft_utils.py", line 153, in get_peft_kwargs
    r = lora_alpha = list(rank_dict.values())[0]
IndexError: list index out of range

**Comment by OleehyO** [comment]
CogVideoX-Fun uses a different prefix key for inserting the adapter compared to the `peft` library, so you can't directly use the CogVideo project code to load the LoRA layers.
